services:
  - type: web
    name: blfantasy-api
    env: python
    plan: free  # Updated from deprecated 'starter' plan
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: blfantasy-postgres
          property: connectionString

  - type: worker
    name: blfantasy-worker
    env: python
    plan: free  # Updated from deprecated 'starter' plan
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.jobs.worker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blfantasy-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: cron
    name: daily-ingest
    env: python
    schedule: "0 4 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.jobs.ingest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blfantasy-postgres
          property: connectionString

  - type: cron
    name: prematch-pull
    env: python
    schedule: "0 */2 * * 5,6,0"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.jobs.prematch
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blfantasy-postgres
          property: connectionString

databases:
  - name: blfantasy-postgres
    plan: basic-256mb  # Updated from deprecated 'starter' plan
    region: frankfurt
