services:
  - type: web
    name: blfantasy-api
    env: python
    plan: starter
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
      - key: REDIS_URL
      - key: SECRET_KEY
      - key: API_FOOTBALL_KEY

  - type: worker
    name: blfantasy-worker
    env: python
    plan: starter
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python -m jobs.worker
    envVars:
      - key: DATABASE_URL
      - key: REDIS_URL
      - key: SECRET_KEY
      - key: API_FOOTBALL_KEY

  - type: cron
    name: daily-ingest
    env: python
    schedule: "0 4 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m jobs.ingest
    envVars:
      - key: DATABASE_URL
      - key: REDIS_URL
      - key: SECRET_KEY
      - key: API_FOOTBALL_KEY

  - type: cron
    name: prematch-pull
    env: python
    schedule: "0 */2 * * 5,6,0"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m jobs.prematch
    envVars:
      - key: DATABASE_URL
      - key: REDIS_URL
      - key: SECRET_KEY
      - key: API_FOOTBALL_KEY

databases:
  - name: blfantasy-postgres
    plan: starter

keyValues:
  - name: blfantasy-cache